<?php
require_once __DIR__ . '/../lib/bootstrap.php';
$user = kcmc_require_role(['pastor_admin', 'recovery_admin']);
kcmc_private_headers();
$data=kcmc_content();
$announcementIndex=kcmc_featured_announcement_index(is_array($data['announcements']??null)?$data['announcements']:[]);
$a=$announcementIndex!==null&&isset($data['announcements'][$announcementIndex])?$data['announcements'][$announcementIndex]:['id'=>'owner-announcement'];
$msg=(string)($_GET['msg']??'');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KCMC Publishing Desk</title><link rel="stylesheet" href="<?=kcmc_h(kcmc_url('styles.css'))?>"><style>
body{background:#eef2f4;color:#17324c;color-scheme:light}.desk{width:min(1180px,calc(100% - 28px));margin:24px auto 80px}.desk .eyebrow{color:#745221}.desk :is(a,button,input,select,textarea):focus-visible{outline:3px solid #174d75;outline-offset:3px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center}.top a{font-weight:800}.signout-form{display:inline}.signout-form button{border:0;background:transparent;padding:0;color:inherit;text-decoration:underline;font:inherit;font-weight:800;cursor:pointer}.panel{background:#fff;border:1px solid #dce3e7;border-radius:18px;padding:22px;margin:18px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel input,.panel textarea,.panel select{width:100%;padding:11px;border:1px solid #cbd5dc;border-radius:9px;margin:5px 0 12px;font:inherit;background:#fff;color:#17324c}.panel textarea{min-height:110px}.row{display:grid;grid-template-columns:1.4fr 2.6fr .7fr .9fr 1.2fr;gap:10px;align-items:end;border-top:1px solid #edf0f2;padding-top:12px;margin-top:12px}.event-date-times{display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:8px}.event-extra{display:grid;grid-template-columns:1fr 2fr;gap:10px;grid-column:1/-1}.event-extra textarea{min-height:72px}.btnx{border:0;background:#17324c;color:white;padding:12px 16px;border-radius:999px;font-weight:800;cursor:pointer}.danger{background:#8d2d2d}.ok{background:#e6f3e7;color:#215b2d;padding:10px 14px;border-radius:10px}.muted{color:#607080}@media(max-width:850px){.grid,.row,.event-date-times,.event-extra{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="desk"><div class="top"><div><p class="eyebrow">KCMC CONNECT • VERSION 3</p><h1>Publishing Desk</h1><p class="muted">Publish approved church content while member prayer stays private.</p></div><div><a href="<?=kcmc_h(kcmc_url())?>">View site</a> · <a href="<?=kcmc_h(kcmc_url('member/'))?>">Member home</a> · <a href="<?=kcmc_h(kcmc_url('admin/users.php'))?>">Access</a><?php if(kcmc_can_moderate_prayers($user)): ?> · <a href="<?=kcmc_h(kcmc_url('admin/prayers.php'))?>">Prayer approvals</a><?php endif; ?> · <form class="signout-form" method="post" action="<?=kcmc_h(kcmc_url('member/logout.php'))?>"><input type="hidden" name="csrf" value="<?=kcmc_h(kcmc_csrf())?>"><button type="submit">Sign out</button></form></div></div><?php if($msg): ?><p class="ok"><?=kcmc_h($msg)?></p><?php endif; ?>
<form method="post" action="<?=kcmc_h(kcmc_url('admin/save.php'))?>"><input type="hidden" name="csrf" value="<?=kcmc_h(kcmc_csrf())?>">
<section class="panel"><h2>Church contact</h2><div class="grid"><label>Phone<input name="contact_phone" value="<?=kcmc_h((string)($data['contact']['phone']??''))?>"></label><label>Email<input type="email" name="contact_email" value="<?=kcmc_h((string)($data['contact']['email']??''))?>" required></label><label>Office hours<input name="contact_hours" value="<?=kcmc_h((string)($data['contact']['office_hours']??''))?>"></label><label>Address<input name="contact_address" value="<?=kcmc_h((string)($data['contact']['address']??''))?>"></label></div></section>
<section class="panel"><h2>Featured announcement</h2><p class="muted">Priority 100 appears first. Hidden items disappear immediately. Expired items disappear automatically.</p><input type="hidden" name="announcement_id" value="<?=kcmc_h((string)($a['id']??'owner-announcement'))?>"><div class="grid"><label>Title<input name="announcement_title" value="<?=kcmc_h((string)($a['title']??''))?>"></label><label>Priority<input type="number" name="announcement_priority" min="0" max="100" value="<?=kcmc_h((string)($a['priority']??50))?>"></label></div><label>Message<textarea name="announcement_body"><?=kcmc_h((string)($a['body']??''))?></textarea></label><div class="grid"><label>Status<select name="announcement_status"><option value="published" <?=($a['status']??'published')==='published'?'selected':''?>>Published</option><option value="hidden" <?=($a['status']??'')==='hidden'?'selected':''?>>Hidden</option></select></label><label>Expires at<input type="datetime-local" name="announcement_expires" value="<?=kcmc_h(kcmc_local_date_value((string)($a['expires_at']??''),'Y-m-d\TH:i'))?>"></label></div></section>
<section class="panel"><h2>Sunday bulletin</h2><div class="grid"><label>Title<input name="bulletin_title" value="<?=kcmc_h((string)($data['bulletin']['title']??''))?>"></label><label>Date<input type="date" name="bulletin_date" value="<?=kcmc_h((string)($data['bulletin']['date']??''))?>"></label></div><label>Welcome line<input name="bulletin_welcome" value="<?=kcmc_h((string)($data['bulletin']['welcome']??''))?>"></label><label>Bulletin notes — one per line<textarea name="bulletin_notes"><?=kcmc_h(implode("\n",$data['bulletin']['notes']??[]))?></textarea></label></section>
<section class="panel"><h2>Events</h2><p class="muted">Start and end times power the calendar download. Set an event to Hidden to remove it without deleting its record.</p><?php foreach(($data['events']??[]) as $i=>$event): if(!is_array($event))continue; ?><div class="row"><label>Title<input name="events[<?=$i?>][title]" value="<?=kcmc_h((string)($event['title']??''))?>"></label><div class="event-date-times"><label>Date<input type="date" name="events[<?=$i?>][date]" value="<?=kcmc_h((string)($event['date']??''))?>"></label><label>Start time<input name="events[<?=$i?>][time]" value="<?=kcmc_h((string)($event['time']??''))?>" placeholder="4:30 PM"></label><label>End time<input name="events[<?=$i?>][end_time]" value="<?=kcmc_h((string)($event['end_time']??''))?>" placeholder="6:30 PM"></label></div><label>Priority<input type="number" name="events[<?=$i?>][priority]" value="<?=kcmc_h((string)($event['priority']??50))?>"></label><label>Status<select name="events[<?=$i?>][status]"><option value="published" <?=($event['status']??'published')==='published'?'selected':''?>>Published</option><option value="hidden" <?=($event['status']??'')==='hidden'?'selected':''?>>Hidden</option></select></label><label>Expires<input type="date" name="events[<?=$i?>][expires]" value="<?=kcmc_h(kcmc_local_date_value((string)($event['expires_at']??'')))?>"></label><div class="event-extra"><label>Location<input name="events[<?=$i?>][location]" value="<?=kcmc_h((string)($event['location']??'KCMC'))?>"></label><label>Description<textarea name="events[<?=$i?>][description]"><?=kcmc_h((string)($event['description']??''))?></textarea></label></div><input type="hidden" name="events[<?=$i?>][id]" value="<?=kcmc_h((string)($event['id']??''))?>"></div><?php endforeach; ?></section>
<button class="btnx" type="submit">Publish changes</button> <a class="btnx" style="display:inline-block;text-decoration:none" href="<?=kcmc_h(kcmc_url('admin/backup.php'))?>">Download backup</a>
</form></main></body></html>
