#!/usr/bin/env python3
"""Offline browser regression for publication text; no live data or credentials.

Requires: playwright and a Chromium browser. Uses mocked project/media endpoints,
so this verifies the actual editor's browser behavior, not server authorization.
"""
import argparse
import html
import json
import os
from pathlib import Path
import re
import shutil

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / 'KCMC-Connect-Phase6-Recreated/admin/publication-designer.php'


def fixture_html(source):
    source = re.sub(r'\A<\?php.*?\?>', '', source, count=1, flags=re.S)

    def replace(match):
        expr = match.group(1)
        path = re.search(r"kcmc_url\('([^']+)'\)", expr)
        if path:
            value = '/' + path.group(1)
            return json.dumps(value) if expr.startswith('json_encode(') else html.escape(value, quote=True)
        if expr == 'json_encode(kcmc_csrf(), JSON_UNESCAPED_SLASHES)':
            return json.dumps('synthetic-text-fixture-csrf')
        raise AssertionError('Unexpected PHP expression in browser fixture: ' + expr)

    rendered = re.sub(r'<\?=(.*?)\?>', replace, source, flags=re.S)
    assert '<?' not in rendered, 'Fixture must not leave executable PHP'
    return rendered


def run(source_path, screenshot=None):
    source = source_path.read_text()
    rendered = fixture_html(source)
    store, errors, saves = {}, [], []

    def fixture_request(url, method, body):
        if url == '/admin/publication-projects.php':
            if method == 'POST':
                project = json.loads(body)
                assert project.pop('csrf') == 'synthetic-text-fixture-csrf'
                project['id'] = project.get('id') or f'fixture-{len(store) + 1}'
                project['updated'] = '2026-10-06T23:00:00Z'
                store[project['id']] = project
                # Match existing pub_text trimming without touching real storage.
                for pg in project['pages']:
                    for item in pg['items']:
                        if item['type'] == 'text':
                            item['text'] = item['text'].strip(' \t\n\r\0\x0b')
                saves.append(project)
                return {'ok': True, 'project': project}
            return {'ok': True, 'projects': list(store.values())}
        if url == '/admin/publication-media.php':
            return {'ok': True, 'media': []}
        raise AssertionError('Offline fixture: unexpected request ' + url)

    with sync_playwright() as pw:
        executable = os.environ.get('CHROMIUM_PATH') or shutil.which('chromium')
        options = {'headless': True, 'args': ['--no-sandbox']}
        if executable:
            options['executable_path'] = executable
        browser = pw.chromium.launch(**options)
        page = browser.new_page(viewport={'width': 1500, 'height': 1100})
        page.on('pageerror', lambda error: errors.append(str(error)))
        page.route('**/*', lambda route: route.abort())
        page.expose_function('__fixtureRequest', fixture_request)
        page.evaluate('''() => {
            window.print = () => { window.__printed = true; };
            window.fetch = async (url, options = {}) => {
                const payload = await window.__fixtureRequest(url, options.method || 'GET', options.body || null);
                return {ok: true, json: async () => payload};
            };
        }''')
        page.set_content(rendered)
        page.wait_for_function("document.querySelector('#savedList').textContent.includes('No shared projects')")

        def save_as(name):
            prior = len(saves)
            page.locator('#projectName').fill(name)
            page.locator('#saveBtn').click()
            page.wait_for_function("document.querySelector('#status').textContent === 'Saved for KCMC admins'")
            assert len(saves) == prior + 1
            return saves[-1]

        # A real built-in template starts with <br> nodes generated by innerText.
        page.locator('[data-template="bulletin"]').click()
        expected = 'Welcome\n\nPrelude\nOpening Hymn\nPrayer\nScripture\nMessage\nOffering\nClosing Hymn\nBenediction'
        p = save_as('Round-trip bulletin')
        assert p['pages'][0]['items'][1]['text'] == expected, ('Bulletin line breaks lost on save', p['pages'][0]['items'][1]['text'])
        page.locator('#newBtn').click()
        page.locator('#savedList button').filter(has_text='Round-trip bulletin').click()
        body = page.locator('#page .item[data-type="text"]').nth(1)
        assert body.inner_text() == expected, 'Reopening must preserve paragraphs'
        assert body.evaluate("el => getComputedStyle(el).whiteSpace") == 'pre-wrap'
        print('PASS: built-in bulletin save and reopen retain blank lines')

        # Duplicating, changing pages and saving again must not flatten text.
        page.locator('#duplicatePage').click()
        p = save_as('Round-trip bulletin')
        assert len(p['pages']) == 2
        assert all(pg['items'][1]['text'] == expected for pg in p['pages'])
        page.locator('#prevPage').click()
        page.locator('#nextPage').click()
        assert page.locator('#page .item[data-type="text"]').nth(1).inner_text() == expected
        page.locator('#duplicateBtn').click()
        copy = save_as('Round-trip copy')
        assert copy['id'] != p['id'] and copy['pages'] == p['pages']
        print('PASS: multipage navigation, page duplicate and project copy preserve text')

        # Browser-generated line blocks, pasted paragraphs, markup-as-text and soft wrap.
        cases = [
            ('br-nodes', 'First<br><br>Third', 'First\n\nThird', False),
            ('enter-divs', 'First<div>Second</div><div><br></div><div>Fourth</div>', 'First\nSecond\n\nFourth', False),
            ('pasted-paragraphs', '<p>First</p><p>Second</p>', 'First\n\nSecond', False),
            ('literal-markup', '<b>Not HTML</b>\n<script>plain text</script>\n& < >', '<b>Not HTML</b>\n<script>plain text</script>\n& < >', True),
            ('spaces-and-unicode', 'Scripture  \n\nGrace • peace ✝', 'Scripture  \n\nGrace • peace ✝', True),
            ('soft-wrap', 'This sentence wraps in a narrow text box without adding a hard line break.', 'This sentence wraps in a narrow text box without adding a hard line break.', True),
            ('blank', '', '', True),
        ]
        for name, content, want, literal in cases:
            page.locator('#newBtn').click()
            page.locator('#page').evaluate('el => el.innerHTML = ""')
            page.locator('#addText').click()
            page.locator('#page .item').evaluate('''(el, c) => {
                const handle = el.querySelector('.handle');
                if(c.literal) el.textContent = c.content; else el.innerHTML = c.content;
                el.appendChild(handle);
                if(c.name === 'soft-wrap') el.style.width = '110px';
            }''', {'content': content, 'literal': literal, 'name': name})
            captured = save_as(name)
            got = captured['pages'][0]['items'][0]['text']
            assert got == want, (name, 'serialized text mismatch', repr(got), repr(want))
            page.locator('#newBtn').click()
            page.locator('#savedList button').filter(has_text=name).click()
            restored = page.locator('#page .item[data-type="text"]')
            assert restored.inner_text() == want, (name, 'restored text mismatch', repr(restored.inner_text()))
            if name == 'literal-markup':
                assert restored.locator('script,b').count() == 0, 'Saved text must not become HTML'
            print('PASS:', name)

        page.locator('#savedList button').filter(has_text='Round-trip copy').click()
        page.locator('#printBtn').click()
        page.wait_for_function('window.__printed === true')
        page.emulate_media(media='print')
        assert page.locator('#printPages .page').count() == 2
        for printed in page.locator('#printPages .page').all():
            text = printed.locator('.item[data-type="text"]').nth(1)
            assert text.inner_text() == expected, 'Print layout lost hard line breaks'
            assert text.evaluate('el => getComputedStyle(el).whiteSpace') == 'pre-wrap'
            assert text.evaluate('el => getComputedStyle(el).paddingLeft') == '6px'
            assert printed.locator('.handle').count() == 0
        assert errors == [], errors
        if screenshot:
            page.screenshot(path=str(screenshot), full_page=True)
        browser.close()
        print('PASS: print view retains two pages, paragraph spacing and editor text inset')
        print('Publication text round-trip: 10 browser checks passed; endpoints mocked, no live storage touched.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=DEFAULT_SOURCE)
    parser.add_argument('--screenshot', type=Path)
    args = parser.parse_args()
    run(args.source, args.screenshot)
