<?php
require_once __DIR__ . '/lib/bootstrap.php';
$content = kcmc_content();
$news = is_array($content['news'] ?? null) ? $content['news'] : [];
$reflection = is_array($news['reflection'] ?? null) ? $news['reflection'] : [];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Current KCMC Church News presented as accessible app content."><title>Church News • KCMC Connect</title><link rel="stylesheet" href="styles.css?v=3.0.0"><style>
.news-page{width:min(1050px,calc(100% - 30px));margin:40px auto 80px}.news-page>a{color:#f3d99e;font-weight:850}.news-page h1{font-family:Georgia,serif;font-size:clamp(3rem,8vw,5.6rem);font-weight:400;line-height:.95;margin:.2em 0}.news-page .lead{max-width:760px}.news-page-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:30px 0}.news-page-stat,.news-page-card{background:rgba(255,255,255,.055);border:1px solid #29475b;border-radius:19px;padding:20px}.news-page-stat b{display:block;font:400 2.8rem/1 Georgia,serif;color:#e5b85f}.news-page-stat p{margin:.6em 0 0;color:#b9c8d0}.news-page-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.news-page-card.featured{grid-column:1/-1;background:linear-gradient(140deg,rgba(68,116,143,.32),rgba(255,255,255,.04))}.news-page-card h2{font-family:Georgia,serif;font-size:2rem;font-weight:400;margin:.25em 0}.news-page-card p,.news-page-card li{line-height:1.65}.news-page-card ul{padding-left:1.2rem}@media(max-width:760px){.news-page-stats,.news-page-grid{grid-template-columns:1fr 1fr}.news-page-card.featured{grid-column:1/-1}}@media(max-width:520px){.news-page-stats,.news-page-grid{grid-template-columns:1fr}.news-page-card.featured{grid-column:auto}}
</style></head><body><main class="news-page"><a href="./#news">← KCMC Connect</a><p class="eyebrow"><?=kcmc_h((string)($news['month']??''))?> • Issue #<?=kcmc_h((string)($news['issue']??''))?></p><h1><?=kcmc_h((string)($news['title']??'Church News'))?></h1><p class="lead muted">Newsletter information is rebuilt here as readable, accessible app content. Photos of the printed newsletter pages are never published.</p>
<div class="news-page-stats"><?php foreach(array_slice($news['highlights']??[],0,4) as $highlight): ?><article class="news-page-stat"><b><?=kcmc_h((string)($highlight['stat']??''))?></b><strong><?=kcmc_h((string)($highlight['label']??''))?></strong><p><?=kcmc_h((string)($highlight['detail']??''))?></p></article><?php endforeach; ?></div>
<div class="news-page-grid"><article class="news-page-card featured"><p class="eyebrow">PASTORAL REFLECTION</p><h2><?=kcmc_h((string)($reflection['title']??''))?></h2><p><?=kcmc_h((string)($reflection['body']??''))?></p><p><strong>Scripture:</strong> <?=kcmc_h((string)($reflection['scripture']??''))?></p></article>
<?php foreach($news['sections']??[] as $section): ?><article class="news-page-card"><p class="eyebrow"><?=kcmc_h((string)($section['label']??'CHURCH NEWS'))?></p><h2><?=kcmc_h((string)($section['title']??''))?></h2><p><?=kcmc_h((string)($section['body']??''))?></p></article><?php endforeach; ?>
<article class="news-page-card"><p class="eyebrow">GROUPS</p><h2>Find your weekly rhythm</h2><ul><?php foreach($news['groups']??[] as $item): ?><li><?=kcmc_h((string)$item)?></li><?php endforeach; ?></ul></article>
<article class="news-page-card"><p class="eyebrow">WAYS TO HELP</p><h2>Practical ministry this month</h2><ul><?php foreach($news['outreach']??[] as $item): ?><li><?=kcmc_h((string)$item)?></li><?php endforeach; ?></ul></article></div>
</main></body></html>
