<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/timeclock.php';
$user=kcmc_require_login(); kcmc_private_headers(); $error=''; $message='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 if(!kcmc_verify_csrf($_POST['csrf']??null)){http_response_code(403);$error='Your session expired. Reload and try again.';}
 else {try{kcmc_timeclock_mutate((string)$user['id'],(string)($_POST['action']??''),$_POST);$message='Time clock updated.';}catch(Throwable $e){$error=$e->getMessage();}}
}
$open=kcmc_timeclock_open_entry((string)$user['id']); $entries=kcmc_timeclock_entries_for((string)$user['id']); [$periodStart,$periodEnd]=kcmc_timeclock_period();
$period=array_values(array_filter($entries,fn($e)=>($e['work_date']??'')>=$periodStart&&($e['work_date']??'')<=$periodEnd)); $total=array_sum(array_map(fn($e)=>(int)($e['net_minutes']??0),$period));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Time Clock • KCMC Connect</title><link rel="stylesheet" href="<?=kcmc_h(kcmc_url('styles.css'))?>"><style>main{width:min(850px,calc(100% - 28px));margin:24px auto 70px}.card{background:#fff;border:1px solid #dce3e7;border-radius:18px;padding:20px;margin:16px 0}button,select,textarea{font:inherit}button{padding:12px 18px;border:0;border-radius:999px;background:#17324c;color:#fff;font-weight:800}textarea,select{width:100%;box-sizing:border-box;padding:11px;margin:6px 0 14px}textarea{min-height:100px}.error{background:#fdeaea;padding:12px}.ok{background:#e6f3e7;padding:12px}.entry{border-top:1px solid #ddd;padding:12px 0}.muted{color:#607080}</style></head><body><main><p><a href="<?=kcmc_h(kcmc_url('member/'))?>">← Member home</a></p><h1>Employee Time Clock</h1><p class="muted">Pay period <?=$periodStart?> through <?=$periodEnd?> • <?=number_format($total/60,2)?> hours completed</p><?php if($error):?><p class="error"><?=kcmc_h($error)?></p><?php endif;?><?php if($message):?><p class="ok"><?=kcmc_h($message)?></p><?php endif;?><section class="card"><?php if(!$open):?><h2>Ready to work?</h2><form method="post"><input type="hidden" name="csrf" value="<?=kcmc_h(kcmc_csrf())?>"><input type="hidden" name="action" value="clock_in"><button>Clock In</button></form><?php else:$onBreak=false;foreach(($open['breaks']??[]) as $b)if(empty($b['end_at']))$onBreak=true;?><h2>Clocked in</h2><p>Started <?=kcmc_h(kcmc_local_date_value((string)$open['clock_in_at'],'M j, g:i A'))?></p><?php if($onBreak):?><form method="post"><input type="hidden" name="csrf" value="<?=kcmc_h(kcmc_csrf())?>"><input type="hidden" name="action" value="break_end"><button>End Break</button></form><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=kcmc_h(kcmc_csrf())?>"><input type="hidden" name="action" value="break_start"><button>Start Break</button></form><hr><form method="post"><input type="hidden" name="csrf" value="<?=kcmc_h(kcmc_csrf())?>"><input type="hidden" name="action" value="clock_out"><label>Work category<select name="category" required><option value="">Choose…</option><?php foreach(kcmc_timeclock_categories() as $c):?><option><?=kcmc_h($c)?></option><?php endforeach;?></select></label><label>What did you work on today?<textarea name="description" maxlength="1000" required></textarea></label><button>Clock Out & Complete Day</button></form><?php endif;endif;?></section><section class="card"><h2>This pay period</h2><?php if(!$period):?><p>No completed entries yet.</p><?php endif;?><?php foreach(array_reverse($period) as $e):?><div class="entry"><strong><?=kcmc_h((string)$e['work_date'])?> — <?=number_format(((int)($e['net_minutes']??0))/60,2)?> hrs</strong><br><?=kcmc_h((string)($e['category']??''))?><br><?=nl2br(kcmc_h((string)($e['description']??'')))?></div><?php endforeach;?></section></main></body></html>